train:
  test_size: 0.2
  random_state: 42
  model_name: random_forest  # "logistic_regression"
  random_forest:
    n_estimators: 150
    max_depth: 15
    min_samples_split: 12
    min_samples_leaf: 2
  logistic_regression:
    C: 10
    penalty: "l2"
    solver: 'liblinear'