train:
  test_size: 0.2
  random_state: 42
  model_name: logistic_regression  # "random_forest"
  random_forest:
    n_estimators: 150
    max_depth: 15
    min_samples_split: 12
    min_samples_leaf: 2
  logistic_regression:
    C: 5
    penalty: "l2"
    max_iter: 1000
    solver: 'liblinear'