train:
  test_size: 0.2
  random_state: 42
  model_name: random_forest  # "logistic_regression"
  random_forest:
    n_estimators: 275
    max_depth: 25
    min_samples_split: 14
    min_samples_leaf: 4
  logistic_regression:
    C: 0.5
    penalty: "l2"
    solver: 'liblinear'